version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb-1:27017/the_database?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongodb-1
    networks:
      - backend-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-net

  mongodb-1:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
