services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb-1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--auth"]
    networks:
      - backend-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-net

  todo-backend:
    build: .
    container_name: todo-backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongodb:27017/the_database?authSource=admin
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      - mongodb
      - redis
    networks:
      - backend-net

volumes:
  mongo-data:

networks:
  backend-net:
    driver: bridge
